2024-05-13 16:37:15,601: asyncio: INFO: [Test] Executing the initialize lifecycle method
2024-05-13 16:37:16,786: root: INFO: Current backtesting datetime 2018-01-02 08:30:00-05:00
2024-05-13 16:37:16,787: asyncio: INFO: [Test] Executing the before_market_opens lifecycle method
2024-05-13 16:37:16,788: root: INFO: Current backtesting datetime 2018-01-02 09:30:00-05:00
2024-05-13 16:37:16,788: asyncio: INFO: [Test] Executing the before_starting_trading lifecycle method
2024-05-13 16:37:16,790: asyncio: INFO: [Test] [34mExecuting the on_trading_iteration lifecycle method at 2024-05-13 16:37:16[0m
2024-05-13 16:37:30,614: asyncio: ERROR: [Test] cannot access local variable 'currentPE' where it is not associated with a value
2024-05-13 16:37:30,618: asyncio: ERROR: [Test] Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 923, in run
    self._run_trading_session()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 871, in _run_trading_session
    self._on_trading_iteration()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 262, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 286, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 397, in _on_trading_iteration
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/lumibot/strategies/strategy_executor.py", line 369, in _on_trading_iteration
    on_trading_iteration()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/lumibot/tools/decorators.py", line 34, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/raynergoh/tradingbot/lumibotv2/tbot.py", line 37, in on_trading_iteration
    amountToInvest = (21 / currentPE) * DCA_amount
                           ^^^^^^^^^
UnboundLocalError: cannot access local variable 'currentPE' where it is not associated with a value

2024-05-13 16:37:30,619: asyncio: INFO: [Test] Executing the on_bot_crash event method
2024-05-13 16:37:30,622: root: INFO: Backtesting finished
2024-05-13 16:37:31,071: asyncio: WARNING: [Test] Cannot plot returns because the strategy returns are missing
2024-05-13 16:37:31,198: asyncio: WARNING: [Test] Cannot create a tearsheet because the strategy returns are missing
2024-05-13 16:37:31,198: backtest_stats: INFO: Backtest took 0:00:15.599439 for a speed of 0.000
